name: ${COMPOSE_PROJECT_NAME}

services:
  api:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: base
    container_name: ${COMPOSE_PROJECT_NAME}_api
    working_dir: /var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_ROOT: /var/www/html
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", 'php -r ''exit(@fsockopen("127.0.0.1",9000)?0:1);''']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  web:
    build:
      context: .
      dockerfile: ./apps/backend/docker/nginx/Dockerfile
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      api:
        condition: service_healthy

  caddy:
    image: caddy:2
    container_name: ${COMPOSE_PROJECT_NAME}_caddy
    restart: unless-stopped
    depends_on:
      web:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./infra/ssl/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./infra/ssl/certs:/etc/certs:ro
    profiles: ["ssl"]

  db:
    image: mysql:8.4
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_db}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_pass}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./infra/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -u${MYSQL_USER:-app_user} -p${MYSQL_PASSWORD:-app_pass} -h localhost",
        ]
      interval: 20s
      timeout: 5s
      retries: 10

  cache:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    ports:
      - "${REDIS_PORT:-6380}:6379"

  mail:
    image: axllent/mailpit:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mail
    ports:
      - "8025:8025"
      - "1025:1025"

  frontend:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_ui
    working_dir: /usr/src/app
    environment:
      PNPM_STORE_DIR: /pnpm-store # set for the container, no ${...}
      WEBPACK_POLL: "0"
    command: >
      sh -lc '
        set -euo pipefail;
        corepack enable;
        corepack prepare pnpm@10.15.1 --activate;
        mkdir -p "$PNPM_STORE_DIR" && chmod 777 "$PNPM_STORE_DIR";
        if [ -f pnpm-lock.yaml ]; then
          pnpm install --frozen-lockfile --reporter=append-only;
        else
          pnpm install --no-frozen-lockfile --reporter=append-only;
        fi;
        pnpm run dev
      '
    ports:
      - "${UI_PORT:-5173}:3000"
    volumes:
      - ./apps/frontend:/usr/src/app
      - pnpm_store:/pnpm-store
    profiles: ["ui"]

  horizon:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: base
    container_name: ${COMPOSE_PROJECT_NAME}_horizon
    working_dir: /var/www/html
    command: sh -lc "php artisan horizon"
    depends_on:
      api:
        condition: service_started
      cache:
        condition: service_started
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

  prometheus:
    image: prom/prometheus:latest
    container_name: ${COMPOSE_PROJECT_NAME}_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    profiles: ["monitoring"]

  grafana:
    image: grafana/grafana:latest
    container_name: ${COMPOSE_PROJECT_NAME}_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    profiles: ["monitoring"]

  loki:
    image: grafana/loki:2.9.8
    container_name: ${COMPOSE_PROJECT_NAME}_loki
    command: ["-config.file=/etc/loki/config.yaml"]
    volumes:
      - ./infra/logging/loki/config.yaml:/etc/loki/config.yaml:ro
    ports:
      - "3100:3100"
    profiles: ["logging"]

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: ${COMPOSE_PROJECT_NAME}_otel
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./infra/tracing/otel/config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    profiles: ["tracing"]

  prism:
    image: stoplight/prism:4
    container_name: ${COMPOSE_PROJECT_NAME}_prism
    command: ["mock", "-h", "0.0.0.0", "/openapi/openapi.yaml"]
    volumes:
      - ./infra/mock/openapi.yaml:/openapi/openapi.yaml:ro
    ports:
      - "4010:4010"
    profiles: ["mock"]

volumes:
  db_data:
  vendor_cache:
  composer_cache:
  grafana_data:
  pnpm_store:
  caddy_data:
  caddy_config:
