blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/your-org/capability-laravel-ts-docker-starter/discussions
    about: Please use discussions for general questions.
