name: Feature request
description: Suggest an improvement to the starter
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change useful?
  - type: textarea
    id: implementation
    attributes:
      label: Possible implementation
      description: Optional thoughts on how to implement

