name: CI (release)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Backend build/publish (example)
      # - uses: shivammathur/setup-php@v2
      #   with: { php-version: '8.3', tools: composer }
      # - name: Install backend deps
      #   working-directory: apps/backend
      #   run: composer install --no-dev --prefer-dist --no-progress
      # - name: Package artifact
      #   run: tar -czf backend.tar.gz -C apps/backend .
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: backend-dist
      #     path: backend.tar.gz

      # Frontend build (example)
      # - uses: actions/setup-node@v4
      #   with: { node-version: '22' }
      # - name: Build frontend
      #   run: |
      #     corepack enable
      #     corepack prepare pnpm@10.15.1 --activate
      #     pnpm -C apps/frontend install --frozen-lockfile
      #     pnpm -C apps/frontend build
      # - name: Upload frontend dist
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: frontend-dist
      #     path: apps/frontend/dist

      # Docker image build/push (example)
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      # GitHub Release (example)
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     generate_release_notes: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
