name: CI
on:
  pull_request:
  push:
    branches: [main, "epic/**", "feature/**"]

jobs:
  pint:
    name: Laravel Pint code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Composer install (backend app)
        working-directory: apps/backend
        run: composer install --no-interaction --prefer-dist

      - name: Pint (app + package)
        run: vendor/bin/pint --test . ../../packages/plenipotentiary-laravel

  pest:
    name: Pest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Composer install (backend app)
        working-directory: apps/backend
        run: composer install --no-interaction --prefer-dist

      - name: Pest (backend app)
        working-directory: apps/backend
        run: vendor/bin/pest --colors=always --testsuite=Feature

      - name: Pest (package plenipotentiary-laravel)
        working-directory: packages/plenipotentiary-laravel
        run: |
          composer install --no-interaction --prefer-dist
          vendor/bin/pest --colors=always
